version: '3'
services:
  solr:
    container_name: test-container
    image: solr:slim
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-demo
      - solr create_core -c target
volumes:
  data:
