on:
  release:
    types: [published, edited]

name: build-release

jobs:
  building:
    name: releasing
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get release version
        env:
          RELEASED: ${{ github.event.release.tag_name }}
        run: |
          echo ::set-env name=RELEASE_VERSION::${RELEASED:1}
          echo "github.event.release.tag_name : ${{ github.event.release.tag_name }}"
          echo "github.event.release.upload_url : ${{ github.event.release.upload_url }}"
          echo "github.event_path : ${{ github.event_path }}"
          # cat ${{ github.event_path }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          default: true
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose

      - name: Install cargo deb rpm
        uses: actions-rs/cargo@v1
        if: success()
        with:
          command: install
          args: cargo-deb cargo-rpm

      - name: Run cargo deb
        uses: actions-rs/cargo@v1
        if: success()
        with:
          command: deb
          args: --verbose

      - name: Create binary package
        run: tar -C target/release -czvf target/release/solrcopy-${{ env.RELEASE_VERSION }}-amd64.tar.gz solrcopy

      - name: Install rpm tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends rpm

      - name: Run cargo rpm
        uses: actions-rs/cargo@v1
        if: success()
        with:
          command: rpm
          args: --verbose

      - name: Upload Debian Package
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/debian/solrcopy_${{ env.RELEASE_VERSION }}_amd64.deb
          asset_name: solrcopy_${{ env.RELEASE_VERSION }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload RPM Package
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/rpmbuild/RPMS/x86_64/solrcopy-${{ env.RELEASE_VERSION }}-1.x86_64.rpm
          asset_name: solrcopy-${{ env.RELEASE_VERSION }}-1.x86_64.rpm
          asset_content_type: application/x-rpm

      - name: Upload binary package
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/solrcopy-${{ env.RELEASE_VERSION }}-amd64.tar.gz
          asset_name: solrcopy-${{ env.RELEASE_VERSION }}-amd64.tar.gz
          asset_content_type: application/octet-stream

# end of file
