on:
  release:
    types: [created, published, edited]

name: build-release

jobs:
  building:
    name: releasing
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Parse Release Tag
        id: this_release
        run: echo ::set-output name=this_release::${GITHUB_REF#refs/*/}

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.this_release }}
        run: |
          echo "RELEASE_VERSION IS: $RELEASE_VERSION"
          echo "steps.vars.outputs.this_release : ${{ steps.vars.outputs.this_release }}"
          echo "github.event_path : ${{ github.event_path }}"
          echo "github.event.upload_url : ${{ github.event.upload_url }}"
          cat ${{ github.event_path }}

      # - name: Checkout sources
      #   uses: actions/checkout@v2

      # - name: Install stable toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     profile: default
      #     toolchain: stable
      #     default: true
      #     override: true

      # - name: Run cargo build
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release --verbose

      # - name: Run cargo test
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test 

      # - name: Install cargo deb rpm
      #   uses: actions-rs/cargo@v1
      #   if: success()
      #   with:
      #     command: install
      #     args: cargo-deb 

      # - name: Run cargo deb
      #   uses: actions-rs/cargo@v1
      #   if: success()
      #   with:
      #     command: deb
      #     args: --verbose

      # - name: Upload Release Asset
      #   id: upload-release-asset 
      #   uses: actions/upload-release-asset@v1
      #   if: success()
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #      # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
      #      # See this blog post for more info:                          
      #     asset_path: target/debian/solrcopy_${{ env.GITHUB_REF }}_amd64.deb
      #     asset_name: solrcopy_${{ env.GITHUB_REF }}_amd64.deb
      #     asset_content_type: application/vnd.debian.binary-package

# TODO:
# sudo apt install -y rpm


# end of file
